"""HTML templates + a tiny render helper for the tailored resume and cover
letter PDFs generated by app/api/routes/documents.py.

Kept separate from tailoring.py deliberately -- that module's no-fabrication
guardrail is load-bearing and covered by its own tests, so template markup
(which carries no fabrication risk of its own) lives here instead of adding
unrelated surface area to a file that's meant to stay minimal and auditable.

The resume template mirrors the layout of the candidate's own master resume:
centered header block, underlined all-caps section headers, skills grouped by
category on one line each, and two-column entry headers (name/company/title
on the left, location or link on the right) with an italic sub-line and
bulleted description underneath.
"""

from jinja2 import Environment, select_autoescape


def render_html_template(template_str: str, **context) -> str:
    env = Environment(autoescape=select_autoescape(["html"]))
    return env.from_string(template_str).render(**context)


DEFAULT_RESUME_TEMPLATE = """
<!doctype html>
<html>
<head>
<style>
  /* WeasyPrint applies its own default @page margin on top of any body margin,
     roughly doubling the whitespace -- set the page margin explicitly here and
     leave body margin at 0 so this is the only margin in effect. */
  @page { size: A4; margin: 1.5cm 1.8cm; }
  body { font-family: Helvetica, Arial, sans-serif; color: #1a1d23; margin: 0; font-size: 10pt; line-height: 1.35; }
  .header { text-align: center; margin-bottom: 0.7em; }
  .name { font-size: 20pt; font-weight: 700; letter-spacing: 0.03em; margin: 0; }
  .headline { font-weight: 700; font-size: 10.5pt; margin: 0.3em 0; }
  .contact-line, .links-line { font-size: 9.5pt; color: #333; margin: 0.15em 0; }
  .contact-line a, .links-line a { color: #333; text-decoration: none; }
  h2 { font-size: 11pt; text-transform: uppercase; letter-spacing: 0.04em;
       border-bottom: 1.3px solid #1a1d23; padding-bottom: 0.1em; margin-top: 0.9em; margin-bottom: 0.4em; }
  .summary { font-size: 9.8pt; margin: 0; }
  ul.plain-list { margin: 0; padding-left: 1.1em; }
  ul.plain-list li { margin-bottom: 0.2em; font-size: 9.8pt; }
  .entry { margin-bottom: 0.55em; }
  .entry-header { display: flex; justify-content: space-between; font-weight: bold; font-size: 9.9pt; }
  .entry-header a { color: #1a1d23; }
  .entry-sub { display: flex; justify-content: space-between; font-style: italic; color: #333; font-size: 9.4pt; margin-bottom: 0.15em; }
  .entry-bullets { margin: 0.1em 0 0 0; padding-left: 1.1em; }
  .entry-bullets li { font-size: 9.6pt; margin-bottom: 0.12em; }
</style>
</head>
<body>
  <div class="header">
    <p class="name">{{ candidate.name }}</p>
    {% if candidate.headline %}<p class="headline">{{ candidate.headline }}</p>{% endif %}
    <p class="contact-line">{{ candidate.location }} | {{ candidate.phone }} | {{ candidate.email }}</p>
    {% if candidate.linkedin or candidate.github %}
    <p class="links-line">
      {%- if candidate.linkedin %}<a href="{{ candidate.linkedin }}">LinkedIn</a>{% endif -%}
      {%- if candidate.linkedin and candidate.github %} | {% endif -%}
      {%- if candidate.github %}<a href="{{ candidate.github }}">GitHub</a>{% endif -%}
    </p>
    {% endif %}
  </div>

  {% if summary %}
  <h2>Professional Summary</h2>
  <p class="summary">{{ summary }}</p>
  {% endif %}

  {% if skill_groups %}
  <h2>Technical Skills</h2>
  <ul class="plain-list">
    {% for g in skill_groups %}
    <li><strong>{{ g.category }}:</strong> {{ g.skills | join(", ") }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  {% if education %}
  <h2>Education</h2>
  {% for e in education %}
  <div class="entry">
    <div class="entry-header">
      <span>{{ e.institution }}</span>
      <span>{{ e.location }}</span>
    </div>
    <div class="entry-sub">
      <span>{{ e.degree }}{% if e.field_of_study %} in {{ e.field_of_study }}{% endif %}{% if e.grade %}, {{ e.grade }}{% endif %}</span>
      <span>{{ e.date_range }}</span>
    </div>
    {% if e.bullets %}
    <ul class="entry-bullets">{% for line in e.bullets %}<li>{{ line }}</li>{% endfor %}</ul>
    {% endif %}
  </div>
  {% endfor %}
  {% endif %}

  {% if experience %}
  <h2>Work Experience</h2>
  {% for x in experience %}
  <div class="entry">
    <div class="entry-header">
      <span>{{ x.company }}</span>
      <span>{{ x.location }}</span>
    </div>
    <div class="entry-sub">
      <span>{{ x.role_title }}</span>
      <span>{{ x.date_range }}</span>
    </div>
    {% if x.bullets %}
    <ul class="entry-bullets">{% for line in x.bullets %}<li>{{ line }}</li>{% endfor %}</ul>
    {% endif %}
  </div>
  {% endfor %}
  {% endif %}

  {% if projects %}
  <h2>Key Projects</h2>
  {% for p in projects %}
  <div class="entry">
    <div class="entry-header">
      <span>{{ p.title }}</span>
      {% if p.project_url %}<span><a href="{{ p.project_url }}">Project Link</a></span>{% endif %}
    </div>
    {% if p.bullets %}
    <ul class="entry-bullets">{% for line in p.bullets %}<li>{{ line }}</li>{% endfor %}</ul>
    {% endif %}
  </div>
  {% endfor %}
  {% endif %}

  {% if certifications %}
  <h2>Certifications &amp; Awards</h2>
  <ul class="plain-list">
    {% for c in certifications %}
    <li><strong>{{ c.name }}</strong>{% if c.description %}: {{ c.description }}{% endif %}</li>
    {% endfor %}
  </ul>
  {% endif %}
</body>
</html>
"""

DEFAULT_COVER_LETTER_TEMPLATE = """
<!doctype html>
<html>
<head>
<style>
  /* See DEFAULT_RESUME_TEMPLATE's comment: @page margin replaces body margin
     so WeasyPrint doesn't apply both and double the whitespace. */
  @page { size: A4; margin: 2cm; }
  body { font-family: Helvetica, Arial, sans-serif; font-size: 11pt; color: #1a1d23;
         margin: 0; line-height: 1.5; }
  .date { margin-bottom: 1.5em; }
  .paragraph { margin-bottom: 1em; white-space: pre-wrap; }
</style>
</head>
<body>
  <div class="date">{{ date_str }}</div>
  <p>Dear {{ company }} Hiring Team,</p>
  <div class="paragraph">{{ body }}</div>
  <p>Sincerely,<br>{{ candidate_name }}</p>
</body>
</html>
"""
